local ground_radiator_shift = util.by_pixel(-5, -20)
local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")
local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
	{
		type = "item",
		name = "hm-large-radiator",
		icon = "__heat-managment__/graphics/large-radiator/large-radiator-icon.png",
		icon_size = 64,
		subgroup = "space-platform",
		order = "ea[large-radiator]",
		hidden = false,
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "hm-large-radiator",
		stack_size = 10,
	},
	{
		type = "assembling-machine",
		name = "hm-large-radiator",
		icon = "__TFMG-thermal__/graphics/radiator-ground/radiator-ground-icon.png",
		hidden = false,
		hidden_in_factoriopedia = false,
		flags = { "placeable-neutral", "player-creation" },
		minable = { mining_time = 1, result = "hm-large-radiator" },
		max_health = 2000,
		circuit_wire_max_distance = assembling_machine_circuit_wire_max_distance,
		circuit_connector = circuit_connector_definitions["assembling-machine"],
		collision_box = { { -3.2, -3.2 }, { 3.2, 3.2 } },
		selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
		open_sound = sounds.machine_open,
		close_sound = sounds.machine_close,
		impact_category = "metal",
		working_sound = {
			sound = {
				filename = "__base__/sound/nuclear-reactor-1.ogg",
				volume = 0.45,
				audible_distance_modifier = 0.5,
			},
			fade_in_ticks = 4,
			fade_out_ticks = 20,
		},
		damaged_trigger_effect = hit_effects.entity(),
		graphics_set = {
			animation = {
				layers = {
					{
						filename = "__heat-managment__/graphics/large-radiator/large-radiator-animation.png",
						priority = "high",
						line_length = 10,
						frame_count = 80,
						animation_speed = 0.1,
						shift = ground_radiator_shift,
						width = 590,
						height = 640,
						scale = 0.38,
					},
					{
						filename = "__heat-managment__/graphics/large-radiator/large-radiator-hr-shadow.png",
						priority = "high",
						frame_count = 1,
						repeat_count = 80,
						shift = ground_radiator_shift,
						width = 1200,
						height = 700,
						scale = 0.38,
						draw_as_shadow = true,
					},
				},
			},
			working_visualisations = {
				{
					animation = {
						filename = "__heat-managment__/graphics/large-radiator/large-radiator-emission1.png",
						priority = "high",
						line_length = 10,
						frame_count = 80,
						animation_speed = 0.1,
						shift = ground_radiator_shift,
						width = 590,
						height = 640,
						scale = 0.38,
						blend_mode = "additive",
						draw_as_glow = true,
					},
				},
			},
		},
		crafting_categories = { "radiator" },
		fixed_recipe = "TFMG-heat-radiation",
		crafting_speed = 6,
		energy_usage = "100MW",
		energy_source = {
			type = "heat",
			max_temperature = 1000,
			min_working_temperature = 15,
			default_temperature = 15,
			specific_heat = "20MJ",
			max_transfer = "1GW",
			connections = {
				{ position = { -3, 3 }, direction = defines.direction.south },
				{ position = { 0, 3 }, direction = defines.direction.south },
				{ position = { 3, 3 }, direction = defines.direction.south },
				{ position = { -3, -3 }, direction = defines.direction.north },
				{ position = { 0, -3 }, direction = defines.direction.north },
				{ position = { 3, -3 }, direction = defines.direction.north },
				{ position = { 3, -3 }, direction = defines.direction.east },
				{ position = { 3, 0 }, direction = defines.direction.east },
				{ position = { 3, 3 }, direction = defines.direction.east },
				{ position = { -3, -3 }, direction = defines.direction.west },
				{ position = { -3, 0 }, direction = defines.direction.west },
				{ position = { -3, 3 }, direction = defines.direction.west },
			},
			heat_picture = {
				north = {
					filename = "__TFMG-thermal__/graphics/small-radiator/small-radiator-heat-1.png",
					size = 384,
					scale = 0.5,
					blend_mode = "additive",
					draw_as_glow = true,
					tint = { 0.5, 0.5, 0.5 },
				},
				east = {
					filename = "__TFMG-thermal__/graphics/small-radiator/small-radiator-heat-2.png",
					size = 384,
					scale = 0.5,
					blend_mode = "additive",
					draw_as_glow = true,
					tint = { 0.5, 0.5, 0.5 },
				},
				south = {
					filename = "__TFMG-thermal__/graphics/small-radiator/small-radiator-heat-3.png",
					size = 384,
					scale = 0.5,
					blend_mode = "additive",
					draw_as_glow = true,
					tint = { 0.5, 0.5, 0.5 },
				},
				west = {
					filename = "__TFMG-thermal__/graphics/small-radiator/small-radiator-heat-4.png",
					size = 384,
					scale = 0.5,
					blend_mode = "additive",
					draw_as_glow = true,
					tint = { 0.5, 0.5, 0.5 },
				},
			},
		},
	},
})
